2025-05-06 14:19:27,156 - epic-validation - INFO - Starting EPIC-secuTrial Validation Service
2025-05-06 14:19:27,156 - epic-validation - INFO - Using base directory: /app/data
2025-05-06 14:19:27,157 - epic-validation - INFO - Latest secuTrial export: /app/data/sT-files/export-20250218
2025-05-06 14:19:27,157 - epic-validation - INFO - Latest EPIC export: /app/data/EPIC-files/export-20250404
2025-05-06 14:19:27,158 - epic-validation - INFO - Reading file: /app/data/sT-files/export-20250218/SSR_cases_of_2024.xlsx with extension .xlsx
2025-05-06 14:19:29,390 - epic-validation - INFO - Processing secuTrial export dataframe
2025-05-06 14:19:29,393 - epic-validation - INFO - Successfully processed secuTrial dataframe with shape (1795, 174)
2025-05-06 14:19:29,394 - epic-validation - INFO - Reading file: /app/data/sT-files/export-20250218/REVASC/report_SSR01_20250218-105747.xlsx with extension .xlsx
2025-05-06 14:19:38,207 - epic-validation - INFO - Processing secuTrial export dataframe
2025-05-06 14:19:38,218 - epic-validation - INFO - Successfully processed secuTrial dataframe with shape (4979, 256)
2025-05-06 14:19:38,241 - epic-validation - INFO - Detected encoding for EPIC file: ISO-8859-1
2025-05-06 14:19:38,244 - epic-validation - INFO - Successfully loaded data: secuTrial=(1795, 174), REVASC=(4979, 256), EPIC=(2288, 1)
2025-05-06 14:19:38,245 - epic-validation - INFO - Unnamed columns in df_secuTrial: [nan]
2025-05-06 14:19:38,245 - epic-validation - INFO - Unnamed columns in df_REVASC: [nan]
2025-05-06 14:19:38,258 - epic-validation - INFO - df_secuTrial_w_REVAS size: (1795, 429)
2025-05-06 14:19:38,412 - epic-validation - ERROR - Unexpected error in main function: local variable 'df_EPIC_all' referenced before assignment
Traceback (most recent call last):
  File "/app/src/main.py", line 1012, in main
    if 'FID' not in df_EPIC_all.columns:
UnboundLocalError: local variable 'df_EPIC_all' referenced before assignment
